"""empty message

Revision ID: 145dda83bf8c
Revises: 0c3e2bfeae5c
Create Date: 2016-10-02 22:45:24.948094

"""

# revision identifiers, used by Alembic.
revision = '145dda83bf8c'
down_revision = '0c3e2bfeae5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('subtitle', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('url_slug', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'projects', ['url_slug'])
    op.create_unique_constraint(None, 'projects', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'url_slug')
    op.drop_column('projects', 'subtitle')
    ### end Alembic commands ###
