"""empty message

Revision ID: 216978b47ed3
Revises: e2c5dbcf0f21
Create Date: 2016-10-03 22:15:18.861911

"""

# revision identifiers, used by Alembic.
revision = '216978b47ed3'
down_revision = 'e2c5dbcf0f21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_constraint('projects_url_slug_key', 'projects', type_='unique')
    op.create_unique_constraint(None, 'projects', ['title'])
    op.drop_column('projects', 'url_slug')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_unique_constraint('projects_url_slug_key', 'projects', ['url_slug'])
    op.drop_column('projects', 'title')
    ### end Alembic commands ###
