"""empty message

Revision ID: 43e970a67525
Revises: 821e9c92cd2d
Create Date: 2016-12-02 22:56:46.142169

"""

# revision identifiers, used by Alembic.
revision = '43e970a67525'
down_revision = '821e9c92cd2d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'content2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('content2', postgresql.JSON(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
