"""empty message

Revision ID: 5a20385ac8a5
Revises: 5a602dd82446
Create Date: 2016-12-31 01:48:14.531086

"""

# revision identifiers, used by Alembic.
revision = '5a20385ac8a5'
down_revision = '5a602dd82446'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_complete', sa.String(1), nullable=False, default='n', server_default='n'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_complete')
    ### end Alembic commands ###
