"""empty message

Revision ID: 5a602dd82446
Revises: 9f3bc0217ead
Create Date: 2016-12-27 20:50:02.980646

"""

# revision identifiers, used by Alembic.
revision = '5a602dd82446'
down_revision = '9f3bc0217ead'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'subtitle')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    ### end Alembic commands ###
