"""empty message

Revision ID: 73c27b8ae6b3
Revises: 216978b47ed3
Create Date: 2016-10-03 23:49:20.861266

"""

# revision identifiers, used by Alembic.
revision = '73c27b8ae6b3'
down_revision = '216978b47ed3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('about', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('about', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contact', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('contact', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contact', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'subtitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('resume', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('resume', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('resume', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('user_role', sa.CHAR(length=1), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('users', 'user_role')
    op.alter_column('resume', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resume', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resume', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'subtitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('contact', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contact', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contact', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('about', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('about', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('about', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
