"""empty message

Revision ID: 821e9c92cd2d
Revises: 82b2614cc821
Create Date: 2016-12-02 22:55:14.011417

"""

# revision identifiers, used by Alembic.
revision = '821e9c92cd2d'
down_revision = '82b2614cc821'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('content2', postgresql.JSON(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'content2')
    ### end Alembic commands ###
