"""empty message

Revision ID: 82b2614cc821
Revises: bd59c9a14105
Create Date: 2016-10-12 23:24:51.097371

"""

# revision identifiers, used by Alembic.
revision = '82b2614cc821'
down_revision = 'bd59c9a14105'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url_slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'projects', ['url_slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'url_slug')
    ### end Alembic commands ###
