"""empty message

Revision ID: ad9517c58bc0
Revises: 5a20385ac8a5
Create Date: 2016-12-31 02:11:58.377016

"""

# revision identifiers, used by Alembic.
revision = 'ad9517c58bc0'
down_revision = '5a20385ac8a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_complete')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    ### end Alembic commands ###
