"""empty message

Revision ID: bd59c9a14105
Revises: 73c27b8ae6b3
Create Date: 2016-10-03 23:53:52.684454

"""

# revision identifiers, used by Alembic.
revision = 'bd59c9a14105'
down_revision = '73c27b8ae6b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
