"""empty message

Revision ID: c2f37a0ef6f6
Revises: 145dda83bf8c
Create Date: 2016-10-02 23:25:30.294514

"""

# revision identifiers, used by Alembic.
revision = 'c2f37a0ef6f6'
down_revision = '145dda83bf8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_title_key', 'projects', type_='unique')
    op.drop_column('projects', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('projects_title_key', 'projects', ['title'])
    ### end Alembic commands ###
