"""empty message

Revision ID: e2f63843fc85
Revises: ad9517c58bc0
Create Date: 2016-12-31 02:12:15.090150

"""

# revision identifiers, used by Alembic.
revision = 'e2f63843fc85'
down_revision = 'ad9517c58bc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_complete', sa.String(length=1), server_default='n', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_complete')
    ### end Alembic commands ###
