"""empty message

Revision ID: f0d5f3abe1cc
Revises: 20f63dbd9aad
Create Date: 2016-10-02 00:47:45.421718

"""

# revision identifiers, used by Alembic.
revision = 'f0d5f3abe1cc'
down_revision = '20f63dbd9aad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('update_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'update_date')
    ### end Alembic commands ###
